export const RENTAL_FORM_FIELDS = [
  {
    type: "input",
    name: "landlordName",
    label: "Landlord's Full Name",
    required: true,
    value: "",
    section: "form",
  },
  {
    type: "input",
    name: "tenantName",
    label: "Tenant's Full Name",
    required: true,
    value: "",
    section: "form",
  },
  {
    type: "input",
    name: "propertyAddress",
    label: "Property Address",
    required: true,
    value: "",
    section: "form",
  },
  {
    type: "number",
    name: "rentAmount",
    label: "Rent Monthly Amount (USDT)",
    required: true,
    value: "",
    section: "form",
  },
  {
    type: "number",
    name: "securityDeposit",
    label: "Security Deposit (USDT)",
    required: true,
    value: "",
    section: "form",
  },
  {
    type: "date",
    name: "rentDueDate",
    label: "Rent Due Date",
    required: true,
    value: "",
    section: "form",
  },
  {
    type: "date",
    name: "leaseEndDate",
    label: "Lease End Date",
    required: true,
    value: "",
    section: "form",
  },
  {
    type: "textarea",
    name: "additionalInfo",
    label: "Additional Information",
    value: "",
    section: "additionalInfo",
  },
  {
    type: "checkbox",
    name: "ethCapitalsGains",
    label:
      "The deposit is in ETH. If it grows, I accept part of the rent can be paid with the capital gains.",
    value: false,
    section: "checkboxes",
  },
  {
    type: "checkbox",
    name: "priceInflationAdjustment",
    label: "The rent price will be adjusted annually based on inflation.",
    value: false,
    section: "checkboxes",
  },
];
